version: '2'
services:
  trainer:
    build: 
      context: ./trainer
      dockerfile: Dockerfile
 #   volumes:
 #     - ./trainer:/app 
    environment:
      - MONGO_URL=mongo     
    depends_on:
      - mongo
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
  #  volumes:
  #    - ./api:/app
    environment:
      - PORT=3000
      - MONGO_URL=mongo  
    ports:
      - 3000:3000  
    depends_on:
      - mongo    
  mongo:
    image: mongo
    ports:
      - 27017:27017  