version: '2'
services:
  bot:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/app
    environment:
      - MESSENGER_PAGE_ACCESS_TOKEN=__change_with_page_access_token__
      - MESSENGER_VERIFICATION_CODE=__change_with_very_secret_code__